[package]
name = "emu-chip-8"
version = "0.1.0"
edition = "2021"

[dependencies]
arrayvec = "0.7.2"
rand = "0.8.4"
pixels = "0.11.0"
winit = "0.27.5"
clap = { version = "^4.0.29", features = ["derive"] }
